{
	"version": 1569189379,
	"fileList": [
		"data.js",
		"c2runtime.js",
		"jquery-2.1.1.min.js",
		"offlineClient.js",
		"images/bolapraia-sheet0.png",
		"images/sprite5-sheet0.png",
		"images/espinho-sheet0.png",
		"images/casaarvore-sheet0.png",
		"images/fundo-sheet0.png",
		"images/plataformaflutuante-sheet0.png",
		"images/macaco-sheet0.png",
		"images/fundonatalino-sheet0.png",
		"images/nuvem-sheet0.png",
		"images/sprite2-sheet0.png",
		"images/sprite3-sheet0.png",
		"images/sprite-sheet0.png",
		"images/sprite4-sheet0.png",
		"images/nuvem1-sheet0.png",
		"images/sprite7-sheet0.png",
		"images/nuvem2-sheet0.png",
		"images/banana-sheet0.png",
		"images/estrela-sheet0.png",
		"images/sprite6-sheet0.png",
		"images/sprite8-sheet0.png",
		"media/macacomorrendo.ogg",
		"media/queen - we are the champions cortado.ogg",
		"media/up.ogg",
		"icon-16.png",
		"icon-32.png",
		"icon-114.png",
		"icon-128.png",
		"icon-256.png",
		"loading-logo.png"
	]
}